-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 23, 2023 at 12:53 PM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `shoppingcart`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

CREATE TABLE `recipes` (
  `rid` int(11) NOT NULL,
  `rname` text NOT NULL,
  `rdesc` text NOT NULL,
  `rimg` text NOT NULL,
  `rlink` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`rid`, `rname`, `rdesc`, `rimg`, `rlink`) VALUES
(1, 'Amla Chutney', '<p>\r\n<b>Ingredients of Amla Chutney</b>\r\n<ul>\r\n<li>1 Tbsp oil</li>\r\n<li>1 Tbsp saunf</li>\r\n<li>1 cup boiled amla</li>\r\n<li>1 tsp dhaniya powder</li>\r\n<li>1 tsp red chilli powder</li>\r\n<li>1 Tbsp ghee</li>\r\n<li>1 tsp bhrami leaves</li>\r\n<li>Salt to taste</li>\r\n</ul>\r\n<b>How to Make Amla Chutney</b>\r\n<ol>\r\n<li>In a pan, take some oil and add sauf in it.</li>\r\n<li>Add boiled pieces of amla. Toss.</li>\r\n<li>Add dhaniya powder, red chilli powder and ghee. Cook for a minute. Now add bhrami leaves and salt. Let it cool.</li>\r\n<li>Blend it in a mixer and serve.</li>\r\n</ol>\r\n</p>', 'amlachutney.jpg', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/U0y0QlEHdjg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>'),
(2, 'Amla Pickle', '<p>\r\n<b>Ingredients of Amla Pickle</b>\r\n<ul>\r\n<li>1/2 kg Amla (Nellikai/ Gooseberry)</li>\r\n<li>1/4 Cup Kashmiri Red Chilli Powder</li>\r\n<li>1/4 cup Salt</li>\r\n<li>1/4 cup Mustard seeds (Rai/ Kadugu) , (kuria-halved)</li>\r\n<li>1/4 cup Jaggery , grated</li>\r\n<li>2 tablespoons Turmeric powder (Haldi)</li>\r\n<li>1 tablespoon Methi Seeds (Fenugreek Seeds) , (kuria-halved)</li>\r\n<li>1 teaspoon Asafoetida (hing)</li>\r\n<li>1-1/2 Cup Peanut oil</li>\r\n</ul>\r\n<b>How to Make Amla Pickle</b>\r\n<ol>\r\n<li>To begin making Amla Achaar Recipe | Hot & Sweet Indian Gooseberry Pickle, select green, unblemished amla (gooseberry) for this pickle. Wash the Amla, pat dry and prick all over with fork. Keep them in a colander.</li>\r\n<li>Heat up 4-5 cup water in a big saucepan. Keep the colander of Amla over it and cover it. Let the Amla cook on the steam for about 20 minutes. </li>\r\n<li>Meanwhile dry roast the fenugreek kuria on a heated skillet until fragrant. Cool and grind to powder.</li>\r\n<li>Let the amla cool down after steaming. Once it is cooled, remove seed and make small wedges of the cooked amla using a knife. Wear hand gloves while doing so as handling amla for a long time make cause blackening of nails in few cases.</li>\r\n<li>In a big mixing bowl, first spread the Amla wedges. Now sprinkle the Turmeric powder all over it followed by the Fenugreek powder, Hing , Mustard Seed dal , Salt and Red Chili powder.</li>\r\n<li>Mix it nicely with a spatula. Now add in the grated Jaggery and mix again.</li>\r\n<li>Heat up the Oil in a kadai, on a low to medium heat until heated but not fuming. Put off the heat and let the oil cool down a bit. Now add this Oil to the pickle masala and mix very well. </li>\r\n<li>Keep the pickle covered overnight. </li>\r\n<li>Next day oil will float up . Stir it again and fill in clean and dry glass jars. The oil layer should always cover the pickle in the jar. This pickle stays good at room temperature for about 2-3 months. But color may darken slightly, hence you can refrigerate. </li>\r\n<li>Serve Amla Achaar Recipe | Hot & Sweet Indian Gooseberry Pickle as an accompaniment with Carrots & Sweet Potato Stuffed Paratha Recipe or along with Steamed Rice and Thatta Payaru Sambar Recipe (Black Eyed Beans Sambar).\r\n</li>\r\n</ol>\r\n</p>', 'amlapickle.jpg', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/GIndeHSWgeM\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>'),
(3, 'Ashwagandha Tea', '<p>\r\n<b>Ingredients of Ashwagandha Tea</b>\r\n<ul>\r\n<li>1 teaspoon of Ashwagandha powder\r\n</li><li>1 teaspoon of cinnamon powder\r\n</li><li>1 teaspoon of cardamom powder\r\n</li><li>1 teaspoon of ginger powder\r\n</li><li>1 teaspoon of honey\r\n</li><li>1 cup of water\r\n</li>\r\n</ul>\r\n<b>How to Make Ashwagandha Tea</b>\r\n<ol>\r\n</li><li>Bring the water to a boil in a small saucepan.\r\n</li><li>Add the Ashwagandha powder, cinnamon powder, cardamom powder, and ginger powder to the boiling water.\r\n</li><li>Reduce the heat and simmer for 5 minutes.\r\n</li><li>Strain the tea into a cup and add the honey.\r\n</li><li>Stir until the honey is dissolved.\r\n</li><li>Enjoy your Ashwagandha Tea hot or cold.\r\n</li>\r\n</ol>\r\n</p>', 'ashwagandhatea.jpg', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/FGCgHkyfVUo\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>'),
(4, 'Turmeric, Ashwagandha and Carrot soup', '<p>\r\n<b>Ingredients of Turmeric, Ashwagandha and Carrot soup</b>\r\n<ul>\r\n<li>\r\n10g coconut oil\r\n</li><li>1 small onion, diced\r\n</li><li>200g carrot, diced\r\n</li><li>1 medium orange (zest and juice)\r\n</li><li>1tsp turmeric powder\r\n</li><li>1tbsp flax seeds\r\n</li><li>1tsp cumin seeds\r\n</li><li>1tbsp ashwagandha powder\r\n</li><li>600ml water\r\n</li><li>Himalayan salt, red paprika powder, black pepper to taste\r\n</li>\r\n</ul>\r\n<b>How to Make Amla Pickle\r\nTurmeric, Ashwagandha and Carrot soup</b>\r\n<ol>\r\n<li>Slice the carrot and place it in a pot with 600ml water.\r\n</li><li>Boil until carrot is soft.\r\n</li><li>Preheat the wok pan with coconut oil and add chopped onion.\r\n</li><li>Sauté until the onion becomes transparent.\r\n</li><li>Add spices, orange zest, seeds and boiled carrot and keep adding water in which the carrot was cooked. Add turmeric powder. Stir well.\r\n</li><li>Remove from heat and let it cool for a couple of minutes.\r\n</li><li>Transfer everything into a blender and blend until smooth.\r\n</li><li>Add orange juice and ashwagandha powder at the end and stir with a spoon. Heat until ready to serve.\r\n</li><li>Garnish with thin orange slices.\r\n</li>\r\n</ol>\r\n</p>', 'ashwagandhasoup.jpg', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/BZmQPVM4C64\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>'),
(5, 'Aloevera Juice', '<p>\r\n<b>Ingredients of Aloevera Juice</b>\r\n<ul>\r\n<li>\r\nAloevera\r\n</li><li>cucumbers\r\n</li><li>ginger\r\n</li><li>lemon\r\n</li><li>water\r\n</li>\r\n</ul>\r\n<b>How to make Aloevera Juice</b>\r\n<ol>\r\n<li>Add to blender-\r\nWash and dry fresh produce. Cut ends off cucumbers then quarter them so they fit in a blender. Cut lemon in half. Peel ginger.\r\nSqueeze lemon juice into a blender (or peel the lemon and put it all in), add cucumbers, ginger, and water to the blender. Blend on high until mixture is completely broken down and liquefied.\r\n</li><li>Strain the juice-\r\nStrain the liquid through cheese cloth or a nut milk bag, squeezing to extract all of the juice. Discard the leftover pulp.\r\nReturn the strained juice to the blender.\r\n</li><li>Remove aloe spines-\r\nUsing a knife, cut along the sides of the aloe leaf to remove the spines.\r\n</li><li>Remove aloe leaf-\r\nCut along the face of the aloe vera leaf to remove the outer leaf and rind. This will expose the clear gel. Rinse off any yellow liquid that seeps out and cut off and discard any yellow tinted gel.\r\n</li><li>Scoop out gel-\r\nScoop out the clear aloe vera gel from the middle of the leaf.\r\n*Avoid the yellow tinted gel on the outsides closer to the rind.\r\nThe yellow tinted gel is aloe vera latex which is a laxative – definitely not what we want in our refreshing and hydrating juice!\r\n</li><li>Blend aloe juice-\r\nAdd the 2 tbsp of clear aloe vera gel to the blender with the cucumber, lemon, and ginger juice.\r\nBlend on low until the aloe vera gel has fully mixed and incorporated into the juice, about 20 seconds.\r\nPour the fresh juice over ice and enjoy!\r\n</li>\r\n</ol>\r\n</p>', 'aloeverajuice.jpg', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/3RGtb11fDyg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>'),
(6, 'Turmeric - Tomato Thokku', '<p>\r\n<b>Ingredients of Turmeric - Tomato Thokku</b>\r\n<ul>\r\n<li>250 gm fresh haldi/turmeric roots  (about 1 cup chopped)\r\n</li><li>3 large tomatoes (preferably sour or vine-ripened tomatoes)\r\n</li><li>4 green chillies/jalapenos\r\n</li><li>1 tsp methi/fenugreek seeds\r\n</li><li>1 1/2 tsp hing/asafetida powder\r\n</li><li>1 to 2 tsp red chilli powder (depending upon how hot you want)\r\n</li><li>1 tsp mustard seeds\r\n</li><li>10 to 12 curry leaves\r\n</li><li>Salt to taste\r\n</li><li>½ cup sesame oil/any cooking oil\r\n</li>\r\n</ul>\r\n<b>How to make Turmeric - Tomato Thokku</b>\r\n<ol>\r\n<li>Preparing the turmeric-tomato paste:Wash haldi/turmeric roots well, peel and chop into large chunks.\r\n</li><li>Chop tomatoes into large pieces.\r\n</li><li>Blend tomatoes, chopped turmeric roots and green chilies/jalapenos in a food processor or blender to a semi-coarse paste. There is no need to make it too smooth as long as the turmeric roots have blended well.\r\n</li><li>Keep aside.\r\n</li><li>Make the spice powder:In a dry saucepan, roast the methi seeds on low heat until just starting to brown.\r\n</li><li>Stir in 1 tsp of hing powder, mix and remove from heat. The heat in the pan is enough to roast the hing powder.\r\n</li><li>Once cool, pound it in a mortar pestle to a fairly fine powder.\r\n</li><li>To make the turmeric-tomato thokku:Heat oil in a large deep saucepan and once the oil is hot, add the mustard seeds. As they start to pop and crackle, stir in the curry leaves and ½ tsp of hing powder.\r\n</li><li>Saute for a few seconds and then tip in the tomato-turmeric paste.\r\n</li><li>Add red chilli powder and salt to taste, mix well and bring to a boil.\r\n</li><li>Once it comes to a boil, reduce heat to medium low and simmer for about 45 minutes to an hour until you see oil floating on top, stirring in between.\r\n</li><li>Keep adjusting the amount of salt and chilli powder to suit your taste.\r\n</li><li>Just before removing from heat, stir in the pounded methi-hing spice powder and mix well.\r\n</li><li>Let cool and store in dry glass bottles at room temperature for a day or two and then refrigerate for up to 2 weeks.\r\n</li><li>Serve spicy, tangy and healthy turmeric thokku/relish/pickles with dosas (Indian savory rice-lentil crepes), idlis (steamed rice-lentil cakes), flat breads like chapattis/rotis etc.\r\n</li><li>It tastes great mixed with plain rice too!\r\n</li><li>Enjoy and Happy Cooking!\r\n</li>\r\n</ol>\r\n</p>', 'turmericthokku.jpg', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/7LXQg5YB47w\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>'),
(7, 'Neem Juice', '<p>\r\n<b>Ingredients of Neem Juice</b>\r\n<ul>\r\n<li>\r\nNeem\r\n</li><li>water\r\n</li><li>lemon\r\n</li><li>sugar\r\n</li>\r\n</ul>\r\n<b>How to make Neem Juice</b>\r\n<ol>\r\n<li>This is not the neem juice that your mother forces you to drink every morning on an empty stomach. Well, actually, it is that juice but it is no longer bitter. \r\n</li><li>Take some neem leaves and soak them in water for 5 minutes. \r\n</li><li>Put these soaked neem leaves in a grinder and add some water, lemon, and sugar, and churn it well. \r\n</li><li>This drink will freshen and cleanse your body. Lemon and sugar reduce the bitterness of neem and make that drink almost drink-able!\r\n</li>\r\n</ol>\r\n</p>', 'neemjuice.jpg', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/qJTA7upo0C4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>'),
(8, 'Neem Tea', '<p>\r\n<b>Ingredients of Neem Tea</b>\r\n<ul>\r\n<li>\r\nNeem Leaves\r\n</li><li>Water\r\n</li><li>Cinnamon</li>\r\n</ul>\r\n<b>How to make Neem Tea</b>\r\n<ol>\r\n<li>\r\nYou can dry the neem leaves\r\n</li><li>Boil it with water to make tea or you can also purchase dry neem leaves tea bags from the market.\r\n</li><li>Any which way, it will be bitter so we suggest you add some additional items to reduce its bitterness. Sweet and spicy flavours like cinnamon or orange peels blend well in a neem tea and reduce its bitter taste. Even though it won’t taste anything like your everyday tea, but this one will soothe your gastric issues and boost your blood flow.\r\n</li>\r\n</ol>\r\n</p>', 'neemtea.jpg', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/RFgXXUU1EZg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>'),
(9, 'Cumin Water', '<p>\r\n<b>Ingredients of Cumin Water</b>\r\n<ul>\r\n<li>1 teaspoon cumin seeds/jeera\r\n</li><li>2 glasses of water\r\n</li><li>1 teaspoon honey\r\n</li>\r\n</ul>\r\n<b>How to Make Cumin Water</b>\r\n<ol>\r\n<li>In a sauce pan, add water and cumin seeds.\r\n</li><li>Bring the water to a boil.\r\n</li><li>Put the flame on sim and allow the cumin seeds flavor to be absorbed into the water for about 5 minutes.\r\n</li><li>Switch off the flame.\r\n</li><li>Strain the boiled jeera water.\r\n</li><li>Discard the jeera seeds.\r\n</li><li>Add the strained water into a glass.\r\n</li><li>Add honey and stir well.\r\n</li><li>Add few drops of lemon and stir well.\r\n</li><li>Consume it on an empty stomach or after meals.\r\n</li>\r\n</ol>\r\n</p>', 'cuminwater.jpg', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/JsBsAZ6udcc\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>'),
(10, 'Triphala Tea', '<p>\r\n<b>Ingredients of Triphala Tea</b>\r\n<ul>\r\n<li>1/4th tsp Triphala powder \r\n</li><li>250 ml water\r\n</li><li>1-inch Cinnamon stick \r\n</li><li>1 tsp honey or maple syrup(optional)\r\n</li>\r\n</ul>\r\n<b>How to make Triphala Tea</b>\r\n<ol>\r\n<li>Add Triphala powder to water in a pan. \r\n</li><li>Bring to a simmer and let it boil.\r\n</li><li>Add cinnamon sticks and honey or maple syrup if you want, and let it simmer.\r\n</li><li>Remove the tea from the boil and pour yourself a cup.\r\n</li>\r\n</ol>\r\n</p>', 'triphalatea.jpg', '<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/fsS_hpFoSfo\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`rid`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recipes`
--
ALTER TABLE `recipes`
  MODIFY `rid` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
